# Generated by Django 3.2.12 on 2022-02-27 07:48

import django.core.validators
from django.db import migrations, models
import my_music_app.web.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), my_music_app.web.validators.validate_username_chars])),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField(blank=True, null=True, validators=[my_music_app.web.validators.validate_age])),
            ],
        ),
    ]
